import type { ThemeConfig } from 'antd';

import { semanticTokens } from './tokens';

const remToPixels = (value: string) => Number.parseFloat(value) * 16;

export const monergyTheme: ThemeConfig = {
  cssVar: { prefix: 'monergy-ant' },
  hashed: true,
  token: {
    motion: false,
    colorPrimary: semanticTokens.color.brand.primary,
    colorPrimaryHover: semanticTokens.color.brand.primaryHover,
    colorSuccess: semanticTokens.color.state.success,
    colorWarning: semanticTokens.color.state.warning,
    colorError: semanticTokens.color.state.error,
    colorInfo: semanticTokens.color.state.info,
    colorText: semanticTokens.color.neutral['950'],
    colorTextSecondary: semanticTokens.color.neutral['600'],
    colorTextTertiary: semanticTokens.color.neutral['600'],
    colorTextDescription: semanticTokens.color.neutral['600'],
    colorBgBase: semanticTokens.color.neutral['0'],
    colorBorder: semanticTokens.color.neutral['300'],
    fontFamily: semanticTokens.typography.fontFamily,
    fontSize: Number.parseInt(semanticTokens.typography.baseSize, 10),
    lineHeight: semanticTokens.typography.lineHeight,
    fontSizeSM: Number.parseInt(semanticTokens.typography.smallSize, 10),
    fontSizeHeading1: Number.parseInt(semanticTokens.typography.titleSize, 10),
    fontSizeHeading2: 26,
    fontSizeHeading3: Number.parseInt(semanticTokens.typography.sectionSize, 10),
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,
    fontWeightStrong: 600,
    colorTextPlaceholder: '#68768a',
    controlHeight: 40,
    controlHeightLG: 46,
    controlHeightSM: 32,
    padding: remToPixels(semanticTokens.spacing.md),
    paddingSM: remToPixels(semanticTokens.spacing.sm),
    paddingLG: remToPixels(semanticTokens.spacing.lg),
    margin: remToPixels(semanticTokens.spacing.md),
    marginSM: remToPixels(semanticTokens.spacing.sm),
    marginLG: remToPixels(semanticTokens.spacing.lg),
    borderRadius: semanticTokens.radius.control,
    boxShadow: semanticTokens.elevation.panel,
    boxShadowSecondary: semanticTokens.elevation.dialog,
    controlOutline: semanticTokens.focus.color,
    screenSM: remToPixels(semanticTokens.breakpoint.sm),
    screenMD: remToPixels(semanticTokens.breakpoint.md),
    screenLG: remToPixels(semanticTokens.breakpoint.lg),
    screenXL: remToPixels(semanticTokens.breakpoint.xl),
  },
  components: {
    Button: { fontWeight: 500, contentFontSize: 14, primaryShadow: '0 4px 12px #2457a724' },
    Form: { labelFontSize: 14, labelColor: '#263241', verticalLabelPadding: '0 0 8px' },
    Table: { headerBg: '#f5f8fc', headerColor: '#40536d', cellPaddingBlock: 18 },
    Drawer: { footerPaddingBlock: 16, footerPaddingInline: 24 },
    Modal: { titleFontSize: 20, titleLineHeight: 1.4 },
    Alert: { withDescriptionIconSize: 22, withDescriptionPadding: 20 },
  },
};
