import { theme } from 'antd';
import type { ThemeConfig } from 'antd';

import { semanticTokens } from './tokens';

const remToPixels = (value: string) => Number.parseFloat(value) * 16;

export const monergyTheme: ThemeConfig = {
  cssVar: { prefix: 'monergy-ant' },
  hashed: true,
  token: {
    motion: false,
    colorPrimary: semanticTokens.color.brand.primary,
    colorPrimaryHover: semanticTokens.color.brand.primaryHover,
    colorSuccess: semanticTokens.color.state.success,
    colorWarning: semanticTokens.color.state.warning,
    colorError: semanticTokens.color.state.error,
    colorInfo: semanticTokens.color.state.info,
    colorText: semanticTokens.color.neutral['950'],
    colorTextSecondary: semanticTokens.color.neutral['600'],
    colorTextTertiary: semanticTokens.color.neutral['600'],
    colorTextDescription: semanticTokens.color.neutral['600'],
    colorBgBase: semanticTokens.color.neutral['0'],
    colorBorder: semanticTokens.color.neutral['300'],
    fontFamily: semanticTokens.typography.fontFamily,
    fontSize: Number.parseInt(semanticTokens.typography.baseSize, 10),
    lineHeight: semanticTokens.typography.lineHeight,
    fontSizeSM: Number.parseInt(semanticTokens.typography.smallSize, 10),
    fontSizeHeading1: Number.parseInt(semanticTokens.typography.titleSize, 10),
    fontSizeHeading2: 26,
    fontSizeHeading3: Number.parseInt(semanticTokens.typography.sectionSize, 10),
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,
    fontWeightStrong: 600,
    colorTextPlaceholder: '#68768a',
    controlHeight: 40,
    controlHeightLG: 46,
    controlHeightSM: 32,
    padding: remToPixels(semanticTokens.spacing.md),
    paddingSM: remToPixels(semanticTokens.spacing.sm),
    paddingLG: remToPixels(semanticTokens.spacing.lg),
    margin: remToPixels(semanticTokens.spacing.md),
    marginSM: remToPixels(semanticTokens.spacing.sm),
    marginLG: remToPixels(semanticTokens.spacing.lg),
    borderRadius: semanticTokens.radius.control,
    boxShadow: semanticTokens.elevation.panel,
    boxShadowSecondary: semanticTokens.elevation.dialog,
    controlOutline: semanticTokens.focus.color,
    screenSM: remToPixels(semanticTokens.breakpoint.sm),
    screenMD: remToPixels(semanticTokens.breakpoint.md),
    screenLG: remToPixels(semanticTokens.breakpoint.lg),
    screenXL: remToPixels(semanticTokens.breakpoint.xl),
  },
  components: {
    Button: { fontWeight: 500, contentFontSize: 14, primaryShadow: '0 4px 12px #2457a724' },
    Form: { labelFontSize: 14, labelColor: '#263241', verticalLabelPadding: '0 0 8px' },
    Table: { headerBg: '#f5f8fc', headerColor: '#40536d', cellPaddingBlock: 18 },
    Drawer: { footerPaddingBlock: 16, footerPaddingInline: 24 },
    Modal: { titleFontSize: 20, titleLineHeight: 1.4 },
    Alert: { withDescriptionIconSize: 22, withDescriptionPadding: 20 },
  },
};

const midnight = semanticTokens.midnight;
const compact = semanticTokens.compact;
export const midnightTheme: ThemeConfig = {
  ...monergyTheme,
  algorithm: theme.darkAlgorithm,
  token: {
    ...monergyTheme.token,
    colorPrimary: midnight.accent,
    colorPrimaryHover: midnight.accentHover,
    colorPrimaryActive: midnight.accent,
    colorInfo: midnight.info,
    colorSuccess: midnight.success,
    colorWarning: midnight.warning,
    colorError: midnight.danger,
    colorText: midnight.text,
    colorTextSecondary: midnight.secondary,
    colorTextTertiary: midnight.secondary,
    colorTextQuaternary: midnight.secondary,
    colorTextDescription: midnight.secondary,
    colorTextPlaceholder: midnight.secondary,
    colorTextDisabled: midnight.secondary,
    colorBgBase: midnight.canvas,
    colorBgContainer: midnight.sidebar,
    colorBgElevated: midnight.surface,
    colorBgLayout: midnight.canvas,
    colorBgSpotlight: midnight.elevated,
    colorBgContainerDisabled: midnight.surface,
    colorBorder: midnight.controlBorder,
    colorBorderSecondary: midnight.border,
    colorSplit: midnight.border,
    controlItemBgHover: midnight.elevated,
    controlItemBgActive: midnight.selected,
    controlItemBgActiveHover: midnight.selected,
    controlOutline: midnight.accent,
    colorLink: midnight.accent,
    colorLinkHover: midnight.accentHover,
    fontSize: remToPixels(compact.body),
    fontSizeSM: remToPixels(compact.small),
    fontSizeLG: 14,
    fontSizeHeading1: remToPixels(compact.title),
    fontSizeHeading2: remToPixels(compact.section),
    fontSizeHeading3: 16,
    fontSizeHeading4: 14,
    fontSizeHeading5: 13,
    lineHeight: 1.54,
    controlHeight: compact.control,
    controlHeightSM: compact.smallControl,
    controlHeightLG: compact.touchControl,
    borderRadius: compact.controlRadius,
    borderRadiusLG: compact.panelRadius,
    padding: 16,
    paddingLG: 24,
    paddingSM: 12,
    boxShadow: 'none',
    boxShadowSecondary: '0 16px 40px #00000040',
    motionDurationFast: `${String(compact.hoverMs / 1000)}s`,
    motionDurationMid: `${String(compact.motionMs / 1000)}s`,
    motionDurationSlow: `${String(compact.motionMs / 1000)}s`,
  },
  components: {
    Button: {
      fontWeight: 500,
      contentFontSize: 13,
      primaryColor: midnight.canvas,
      primaryShadow: 'none',
      defaultBg: midnight.surface,
      defaultColor: midnight.text,
      defaultBorderColor: midnight.controlBorder,
    },
    Form: {
      labelFontSize: 13,
      labelColor: midnight.text,
      verticalLabelPadding: '0 0 6px',
      itemMarginBottom: 18,
    },
    Input: {
      activeBorderColor: midnight.accent,
      hoverBorderColor: midnight.secondary,
      activeShadow: 'none',
    },
    Select: { optionSelectedColor: midnight.text, optionSelectedBg: midnight.selected },
    Table: {
      headerBg: midnight.surface,
      headerColor: midnight.secondary,
      rowHoverBg: midnight.surface,
      cellPaddingBlock: 8,
      cellPaddingInline: 16,
      borderColor: midnight.border,
      fontSize: 13,
    },
    Drawer: { footerPaddingBlock: 16, footerPaddingInline: 24 },
    Modal: {
      titleFontSize: 18,
      titleLineHeight: 1.45,
      headerBg: midnight.surface,
      contentBg: midnight.surface,
      footerBg: midnight.surface,
    },
    Alert: { withDescriptionIconSize: 18, withDescriptionPadding: 16 },
    Tag: { defaultBg: midnight.surface, defaultColor: midnight.secondary },
  },
};
