<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <AssemblyName>Monergy.Services.Audit</AssemblyName>
    <RootNamespace>Monergy.Services.Audit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../contracts/Monergy.Contracts/Monergy.Contracts.csproj" />
    <ProjectReference Include="../../shared/platform/Monergy.Platform/Monergy.Platform.csproj" />
  </ItemGroup>
</Project>
