<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Monergy.Architecture.Tests</AssemblyName>
    <RootNamespace>Monergy.Architecture.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../shared/platform/Monergy.Platform/Monergy.Platform.csproj" />
    <ProjectReference Include="../../../platform/control-plane/Monergy.Platform.ControlPlane.csproj" />
  </ItemGroup>
</Project>
