<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Monergy.Services.Consent</AssemblyName>
    <RootNamespace>Monergy.Services.Consent</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Monergy.AccessIntegration.Tests" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../shared/platform/Monergy.Platform/Monergy.Platform.csproj" />
  </ItemGroup>
</Project>
