<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <AssemblyName>Monergy.Services.Reporting</AssemblyName>
    <RootNamespace>Monergy.Services.Reporting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="../../shared/platform/Monergy.Platform/Monergy.Platform.csproj" />
  </ItemGroup>
</Project>
