<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../contracts/Monergy.Contracts/Monergy.Contracts.csproj" />
    <ProjectReference Include="../../../services/audit/Monergy.Services.Audit.csproj" />
    <ProjectReference Include="../../../services/reporting/Monergy.Services.Reporting.csproj" />
    <ProjectReference Include="../../../shared/platform/Monergy.Platform/Monergy.Platform.csproj" />
    <ProjectReference Include="../../../build/local/Monergy.LocalAuditHost/Monergy.LocalAuditHost.csproj" />
  </ItemGroup>
</Project>
